version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.api
    user: node
    ports:
      - 3001:3001
  auth:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.auth
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  saecios:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.saecios
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  productos:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.productos
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  pagos:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.pagos
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  gastos:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.gastos
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  metodos-pago:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.metodos-pago
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  reportes:
    build: 
      context: .
      dockerfile: ../dockerfiles/Dockerfile.reportes
    user: node
    links:
      - mongo
      - api
    depends_on: 
      - api
  mongo:
    image: mongo
    restart: always
    ports:
      - 27015:27017
    volumes:
      - ../gestion-data:/data/db/